### ISSUE TITLE
Not able to connect since upgrading to rm 2.12

### ISSUE THREAD

**Issue by luzsat** [nick8325/remarkable-fs#14]
Hi,

first of all, thanks for this very useful tool. I have been using it for years without issues. Unfortunately, I recently upgraded my remarkable (1) software to the latest release, and  remarkable-fs stopped working. It crashes with this error message as soon as I start it:

  Connecting to reMarkable...
Socket exception: Connection reset by peer (104)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 843, in _read_response
    t, data = self._read_packet()
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp.py", line 201, in _read_packet
    x = self._read_all(4)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp.py", line 188, in _read_all
    raise EOFError()
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/remarkable-fs", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/remarkable_fs/__init__.py", line 21, in main
    root = DocumentRoot(conn)
  File "/usr/local/lib/python3.9/dist-packages/remarkable_fs/documents.py", line 246, in __init__
    paths = fnmatch.filter(self.sftp.listdir(), '*.metadata')
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 218, in listdir
    return [f.filename for f in self.listdir_attr(path)]
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 246, in listdir_attr
    t, msg = self._request(CMD_READDIR, handle)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/usr/local/lib/python3.9/dist-packages/paramiko/sftp_client.py", line 845, in _read_response
    raise SSHException("Server connection dropped: {}".format(e))
paramiko.ssh_exception.SSHException: Server connection dropped: 

I wonder if anyone else has encountered the same issue. 

Thanks

**Comment by luzsat** [comment]
**UPDATE**: I seem to have located the problem. 

In connection.py:40 (42 in the repo) the call to 
```python
 ssh.exec_command("while udevadm info -p /devices/soc0/soc/2100000.aips-bus/2184000.usb/power_supply/imx_usb_charger | grep -q POWER_SUPPLY_ONLINE=1; do sleep 1; done; %s; kill $PPID" % on_finish)
```
fails, causing the ssh connection to close.  

Commenting this line gets around the problem.

The power device path seems to be  `/devices/soc0/soc/2100000.aips-bus/21a0000.i2c/i2c-0/0-0055/power_supply/bq27441-0`
and the relevant variable `POWER_SUPPLY_STATUS=Charging`
