### ISSUE TITLE
Bug: Copying of files not possible (performance?)

### ISSUE THREAD

**Issue by schaefischaefi** [nick8325/remarkable-fs#5]
Hi
first of all thank you for all the effort you put into this code. I think this is certainly the right way to go and I want to encourage you to continue. It is great for the all the Linux community (like me) that wan to use the reMarkable under Linux.

Copying of files not possible (performance?)
Description:
The remarkable-filesystem is mounted and the files/folders/documents are show correctly in the file manager. So far everything seems to be ok, but: It is impossible to copy (with "cp" or with the file manager) some of the files to another folder on the laptop. The files are transferred incomplete. No error message is shown. Small files do not seem to be a problem.

Reproducible: yes, always

Analysis:
It seems that only larger files are effected. Analysing the files with a text editor shows, that a stream has started but not finished. The CPU of the laptop goes very high, indicating a performance problem. The command "cp -v" terminates without warning or error aöthough the file is unfinished.

Workaround:
no workaround found

If you have further questions, please let me know.

**Comment by jwittke** [comment]
Hi, 
Trying your script generates some errors:

Password: 
Traceback (most recent call last):
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
    node = cls(self, id, metadata)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in __init__
    self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |########                        | 3/11Traceback (most recent call last):
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
    node = cls(self, id, metadata)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in __init__
    self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |###########                     | 4/11Traceback (most recent call last):
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
    node = cls(self, id, metadata)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in __init__
    self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |#################               | 6/11Traceback (most recent call last):
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
    node = cls(self, id, metadata)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in __init__
    self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |#############################   | 10/11Traceback (most recent call last):
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
    node = cls(self, id, metadata)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in __init__
    self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
    return self._read_response(num)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
    self._convert_status(msg)
  File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |################################| 11/11
Now serving documents at /home/jwittke/Desktop/ReMarkable


When he starts to serve the documents nothings happens and I need to Ctrl-C the script to quit.

I use the new Remakable OS: 1.6.0.6

**Comment by gregeh552** [comment]
The same happens for me on Mac OSX
