### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by jwittke** [nick8325/remarkable-fs#6]
Hi,
Trying your script generates some errors:

Password:
Traceback (most recent call last):
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
node = cls(self, id, metadata)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in init
self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
t, msg = self._request(CMD_STAT, path)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
return self._read_response(num)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
self._convert_status(msg)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |######## | 3/11Traceback (most recent call last):
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
node = cls(self, id, metadata)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in init
self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
t, msg = self._request(CMD_STAT, path)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
return self._read_response(num)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
self._convert_status(msg)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |########### | 4/11Traceback (most recent call last):
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
node = cls(self, id, metadata)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in init
self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
t, msg = self._request(CMD_STAT, path)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
return self._read_response(num)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
self._convert_status(msg)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |################# | 6/11Traceback (most recent call last):
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
node = cls(self, id, metadata)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in init
self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
t, msg = self._request(CMD_STAT, path)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
return self._read_response(num)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
self._convert_status(msg)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |############################# | 10/11Traceback (most recent call last):
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 291, in load_node_without_linking
node = cls(self, id, metadata)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/remarkable_fs/documents.py", line 356, in init
self._size = self.root.sftp.stat(self.id + "." + self.file_type("lines")).st_size
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 493, in stat
t, msg = self._request(CMD_STAT, path)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 813, in _request
return self._read_response(num)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 865, in _read_response
self._convert_status(msg)
File "/home/jwittke/anaconda3/lib/python3.6/site-packages/paramiko/sftp_client.py", line 894, in _convert_status
raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file
Reading document information |################################| 11/11
Now serving documents at /home/jwittke/Desktop/ReMarkable

When he starts to serve the documents nothings happens and I need to Ctrl-C the script to quit.

I use the new Remakable OS: 1.6.0.6

**Comment by gregeh552** [comment]
Same for me on Mac OSX, however the RM is still mounted as a volume and it works except for big documents
<img width="1327" alt="bildschirmfoto 2018-12-28 um 14 59 00" src="https://user-images.githubusercontent.com/38883967/50518211-cfe82780-0ab4-11e9-962f-4c2d0a8f780d.png">

**Comment by bhirsch42** [comment]
I'm having this issue with an M1 Macbook and the Remarkable 2.
