### ISSUE TITLE
BadHostKeyException on 1.7.2.3

### ISSUE THREAD

**Issue by dfioravanti** [nick8325/remarkable-fs#7]
First, thanks a lot for this great piece of software. I recently updated my remarkable to the version 1.7.2.3 of the firmware and remarkable-fs stopped working. What follows is the traceback error.

```
Connecting to reMarkable...
Please enter the root password of your reMarkable.
To find out the password, follow the instructions at:
http://remarkablewiki.com/index.php?title=Methods_of_access#Connecting_via_ssh
Password:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/remarkable_fs/connection.py", line 24, in connect
    ssh.connect('10.11.99.1', username="root")
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 414, in connect
    raise BadHostKeyException(hostname, server_key, our_key)
paramiko.ssh_exception.BadHostKeyException: ('10.11.99.1', <paramiko.rsakey.RSAKey object at 0x7fa881f12f60>, <paramiko.rsakey.RSAKey object at 0x7fa881f120f0>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/remarkable-fs", line 11, in <module>
    load_entry_point('remarkable-fs==0.1.2', 'console_scripts', 'remarkable-fs')()
  File "/usr/local/lib/python3.6/dist-packages/remarkable_fs/__init__.py", line 20, in main
    with connect() as conn:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/dist-packages/remarkable_fs/connection.py", line 30, in connect
    ssh.connect('10.11.99.1', username="root", password=password, look_for_keys=False)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 414, in connect
    raise BadHostKeyException(hostname, server_key, our_key)
paramiko.ssh_exception.BadHostKeyException: ('10.11.99.1', <paramiko.rsakey.RSAKey object at 0x7fa881f02c50>, <paramiko.rsakey.RSAKey object at 0x7fa881f120f0>)
```

**Comment by dfioravanti** [comment]
Just to let people know. It is not a remarkable-fs problem. Apparently the ssh key changed after the last update. All you need to do is to try to ssh into the remarkable and then follow the instructions about changing the key

**Comment by xals** [comment]
You can discard and update the key with the following commands:

```
ssh-keygen -R 10.11.99.1
ssh-keyscan 10.11.99.1 >> "${HOME}/.ssh/known_hosts"
```
